name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aspen

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Run tests
        run: go test

  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aspen

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Run build
        run: go build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: aspen
          path: aspen/aspen
          if-no-files-found: error