name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aspen

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Run tests
        run: go test

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aspen

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Build
        run: go build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: aspen
          path: aspen/aspen
          if-no-files-found: error

  build-win:
    name: build-win
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./aspen

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Build
        run: go build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: aspen
          path: aspen/aspen.exe
          if-no-files-found: error

  upload-examples:
    name: upload-examples
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Upload examples
        uses: actions/upload-artifact@v2
        with:
          name: aspen
          path: examples/
          if-no-files-found: error
